# Generated by Django 2.2.1 on 2019-05-07 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetName', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('propValue', models.PositiveIntegerField()),
                ('fireInsurance', models.PositiveIntegerField()),
                ('squareMeter', models.FloatField()),
                ('rooms', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=999)),
                ('shortDescription', models.CharField(max_length=255)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtor.Realtors')),
            ],
        ),
    ]
