# Generated by Django 2.2.1 on 2019-05-08 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('propertyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Properties')),
            ],
        ),
    ]
