# Generated by Django 2.2.1 on 2019-05-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=3)),
                ('zone', models.CharField(default='Reykjavík', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='zone',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='imagenum',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
