# Generated by Django 2.2.1 on 2019-05-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pzone', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='zone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='imagenum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PropertyArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=3)),
                ('zipZone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.PropertyZone')),
            ],
        ),
    ]
