# Generated by Django 2.2.1 on 2019-05-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20190514_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='zone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='imagenum',
            field=models.PositiveIntegerField(),
        ),
    ]
