# Generated by Django 2.2.1 on 2019-05-14 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20190514_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyarea',
            name='zipZone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.PropertyZone'),
        ),
        migrations.AlterField(
            model_name='propertyzone',
            name='Pzone',
            field=models.CharField(max_length=255),
        ),
    ]
