# Generated by Django 2.2.1 on 2019-05-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20190514_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrpopertyZoneArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.IntegerField(max_length=3)),
                ('area', models.CharField(max_length=255)),
            ],
        ),
    ]
