# Generated by Django 2.2.1 on 2019-05-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_prpopertyzonearea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prpopertyzonearea',
            name='zip',
        ),
    ]
