# Generated by Django 2.2.1 on 2019-05-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_remove_prpopertyzonearea_zip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyArea',
        ),
        migrations.DeleteModel(
            name='PropertyZone',
        ),
    ]
