# Generated by Django 2.2.1 on 2019-05-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20190514_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrpopertyZoneArea',
            new_name='PropertyZoneArea',
        ),
    ]
